export const projects = [
  {
    title: 'E-Commerce My Manga',
    description: "Final project of I'm Henry.",
      image: '/images/manga.png',
      tags: ['Postgress', 'Express', 'React', 'Redux', 'Node, Stripe, Firebase, Formik'],
    source: 'https://github.com/Silbordon/PF-myManga',
    visit: 'https://mymangastore.netlify.app/home',
    id: 0,
  },
  {
    title: 'Videogame Proyect',
    description:"Henry's personal bootcamp project.",
    image: '/images/videogame.jpeg',
    tags: ['React', 'JavaScript', 'Postgress', 'Node', 'Express', 'Redux'],
    source: 'https://github.com/Silbordon/VideoGame-proyect',
    visit: 'https://github.com/Silbordon/VideoGame-proyect',
    id: 1,
  },
  {
    title: 'E-Shopthes',
    description: "CoderHouse Js course project.",
      image: '/images/ecommerceJs.png',
      tags: ['HTML', 'Css', 'Javascript'],
    source: 'https://github.com/Silbordon/ecommerce-JS-CoderHouse',
    visit: 'https://ecommerce-coderhouse-js.netlify.app/',
    id: 2,
  },
  {
    title: 'Cocktails-App',
    description: "Svelte udemi course project.",
    image: '/images/cocktails.png',
    tags: ['Svelte', 'Typescript', 'Css'],
    source: 'https://github.com/Silbordon/cocktailsApp-svelte',
    visit: 'https://cocktails-app-svelte.netlify.app/',
    id: 3,
  },
  {
    title: 'Galery-Sveltekit-App',
    description: "Svelte udemi course project.",
    image: '/images/galery.png',
    tags: ['Svelte', 'Typescript', 'Css'],
    source: 'https://github.com/Silbordon/galery-sveltekit',
    visit: 'https://galery-sveltekit.netlify.app',
    id: 4,
  },
  {
    title: 'Weather-Svelte-App',
    description: "Svelte udemi course project.",
    image: '/images/clima.png',
    tags: ['Svelte', 'Typescript', 'Css'],
    source: 'https://github.com/Silbordon/appClima-svelte',
    visit: 'https://app-clima-svelte.netlify.app/',
    id: 5,
  },
  {
    title: 'Ec-Vivero-MEME',
    description: "CoderHouse React course project.",
      image: '/images/vivero.png',
      tags: ['React', 'bootstrap', 'formik', 'firebase'],
    source: 'https://github.com/Silbordon/insumos-vivero-silvina-bordon',
    visit: 'https://viveromeme-coderhouse.netlify.app/',
    id: 6,
  },
  {
    title: 'Calculator-App',
    description: "React udemi course project.",
    image: '/images/calc.png',
    tags: ['React', 'Css'],
    source: 'https://github.com/Silbordon/Proyecto-calculadora-tutorialUdemy',
    visit: 'https://call-app-oke.web.app/',
    id: 7,
  },
  {
    title: 'Hotel-Reservation-App',
    description: "React udemi course project.",
    image: '/images/reserva.png',
    tags: ['React', 'Redux', 'Material UI'],
    source: 'https://github.com/Silbordon/ejercitacion_hoteleria',
    visit: 'https://ejercitacion-reserva-hotelera.netlify.app/',
    id: 8,
  },
  {
    title: 'Movies-ADA',
    description: "The Rest API of The Movie Database was used.",
    image: '/images/mov.png',
    tags: ['React', 'Antd'],
    source: 'https://github.com/Silbordon/Movies-proyect-ADA',
    visit: 'https://silbordon.github.io/Movies-proyect-ADA/#/',
    id: 9,
  },
  {
    title: 'Search-Comics-ADA',
    description: "The Rest API of the Marvel was used.",
    image: '/images/comics.png',
    tags: ['HTML', 'CSS', 'Js'],
    source: 'https://github.com/Silbordon/Movies-proyect-ADA',
    visit: 'https://maricaroj.github.io/buscador-comics/',
    id: 10,
  },
  {
    title: 'ToDo-List-ADA',
    description: "Crud developed during ADA bootcamp",
    image: '/images/CRUD.png',
    tags: ['HTML', 'CSS', 'Js'],
    source: 'https://github.com/Silbordon/proyectToDoList',
    visit: 'https://silbordon.github.io/proyectToDoList/',
    id: 11,
  },
  {
    title: 'Budget-control-ADA',
    description: "Developed during ADA bootcamp",
    image: '/images/control.png',
    tags: ['React'],
    source: 'https://github.com/Silbordon/control-presupuesto-reactAda',
    visit: 'https://stupefied-nobel-a2bbaf.netlify.app/',
    id: 12,
  },
  {
    title: 'Proyect-Saved-ADA',
    description: "Developed during ADA bootcamp",
    image: '/images/ahor.png',
    tags: ['HTML', 'CSS', 'Js'],
    source: 'https://github.com/Silbordon/ProyectoAhorradasSilvi',
    visit: 'https://silbordon.github.io/ProyectoAhorradasSilvi/',
    id: 13,
  },
  {
    title: 'MEMES-Proyect-ADA',
    description: "Developed during ADA bootcamp",
    image: '/images/MEMES.png',
    tags: ['HTML', 'CSS', 'Js'],
    source: 'https://github.com/Silbordon/Proyecto-MEMES',
    visit: 'https://silbordon.github.io/Proyecto-MEMES/',
    id: 14,
  },
  {
    title: 'Proyect-matcheadas-ADA',
    description: "Developed during ADA bootcamp",
    image: '/images/juego.png',
    tags: ['HTML', 'CSS', 'Js'],
    source: 'https://github.com/Silbordon/proyecto-matcheADAs',
    visit: 'https://silbordon.github.io/proyecto-matcheADAs/',
    id: 15,
  },
];


export const TimeLineData = [

];